zip_url: "http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/data/dblp/dblp.xml.gz"
xml_path: "./xml_data/dblp.xml.gz"
picture_save_path: "./pictures/amount_per_year.pdf"
path_to_logger: "./configs/logging.yaml"
pandas_columns:
  - "author"
  - "title"
  - "year"
  - "school"
  - "editor"
  - "journal"
  - "volume"
  - "ee"
  - "cdrom"
  - "month"
  - "url"
  - "publisher"
  - "series"
  - "number"
  - "isbn"
  - "booktitle"
  - "pages"
  - "crossref"
  - "cite"
  - "address"
  - "note"
  - "chapter"